# Must have a value of at least 1.0.0
# Version: 1.1.0
# Enables users to use a custom PHP version other than the default version. For default and supported PHP versions: <link>   
# Note: As PHP is available by default, user need not mention 'php' as a service unless a custom PHP version is required. 
# Version: 1.2.0
# Adds support for the 'cde-databases' key in your YAML file.
# Version: 1.3.0
# Adds memcached support.
# For more info and supported versions: https://docs.acquia.com/acquia-cloud/develop/pipelines/yaml/#version-key  
version: 1.3.0

# For more info on services supported: https://docs.acquia.com/acquia-cloud/develop/pipelines/yaml/#services-key
services:
  # mysql is supported from version: 1.0.0
  - mysql
  # custom php version is supported from version: 1.1.0
  - php:
      version: 7.3
  # memcached is supported from version: 1.3.0    
  - memcached    
  
events:
  build:
    steps:
      - setup:
          type: script
          script:
            - echo $PIPELINES_SCRIPT_DATA_FILE
            - cat $PIPELINES_SCRIPT_DATA_FILE
            
  pr-merged:
    steps:
      - merge:
          script:
            - echo 'merge!'
  pr-closed:
    steps:
      - close:
          script:
            - echo 'close!'            
          
