# For more acquia-pipelines.yml pipelines examples, see
# https://docs.acquia.com/acquia-cloud/develop/pipelines/yaml/examples/

# Must have a value of at least 1.0.0
# Version: 1.1.0
#   Enables users to use a custom PHP version other than the default version.
#   For default and supported PHP versions, see
#   https://docs.acquia.com/acquia-cloud/develop/pipelines/yaml/#php7
#   Note: As PHP is available by default, user need not mention 'php' as
#   a service unless a custom PHP version is required.
# Version: 1.2.0
#   Adds support for the 'cde-databases' key in your YAML file.
# Version: 1.3.0
#   Adds memcached support.
# For more info and supported versions, see
# https://docs.acquia.com/acquia-cloud/develop/pipelines/yaml/#version-key
version: 1.3.0

# For more info on services supported, see
# https://docs.acquia.com/acquia-cloud/develop/pipelines/yaml/#services-key

services:

  # mysql is supported from version: 1.0.0
  - mysql

  # custom php version is supported from version: 1.1.0
  - php:
      version: 7.3

  # memcached is supported from version: 1.3.0
  - memcached

events:
  build:
    steps:
      - setup:
          type: script
          script:
            - echo 'Start!?'
            - composer validate --no-check-all --ansi
            - composer install
            - mysql -u root -proot -e "CREATE DATABASE drupal"
      - test:
          type: script
          script:
            - ./vendor/bin/phpunit
