version: 1.2.0
services:
  - php:
      version: 7.2
variables:
  global:
    ENABLE_FIPS: TRUE
events:
  build:
    steps:
      # If you have build instructions, put them here. They are not required.
      - build_site:
          script:
            - touch docroot/index.html
            - echo "Pipelines examples 2019.04.02 13:09. You successfully deployed your build to an ODE" > docroot/index.html
  post-deploy:
    steps:
      # Deploy the build artifact to a Cloud on-demand environment.
      - deploy:
          script:
            - pipelines-deploy          
            
            
  
